### ISSUE TITLE
Annotating a module IO with DontTouch that will get de-duplicated fails

### ISSUE THREAD

**Issue by colinschmidt** [freechipsproject/firrtl#689] opened 2017-11-24 17:36 UTC
I think in this particular case I would like the modules to be de-duplicated but leave the debug port (i.e. don't dead code eliminate it).

```
Exception in thread "main" firrtl.transforms.DontTouchAnnotation$DontTouchNotFoundException: Component marked DONT Touch (LaneSequencer_1.io_debug) not found!
```

**Comment by jackkoenig** [comment] 2017-11-24 17:54
My bad, I had a fix for this and then got sidetracked.

This is actually a duplicate of #593 although DCE causes this to be an error.

**Comment by colinschmidt** [comment] 2017-11-24 17:57
Thanks. Easy to workaround for now.

**Closed** 2017-11-29 02:16 UTC
Labels: bug
